controllers/LineupsController.php
<?php
/**
 * Created by PhpStorm.
 * User: Ivan
 * Date: 15.06.2018
 * Time: 7:44
 */

namespace app\controllers;

use app\components\LineupsParser;
use app\models\MatchesLineups;
use app\models\Select;
use app\models\User;
use yii\db\Query;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

class LineupsController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => [
                            'index',
                            'settings',
                            'check-select',
                            'match-subscribe',
                            'match-subscribe-all',
                            'match-subscribe-all',
                            'test'
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        if (\Yii::$app->user->can('lineupsMatches')) {
            $matches = MatchesLineups::find()->where(['and', ['>', 'date', time() - 7200], ['<', 'date', time() + 14400]])->orderBy('date')->all();

            return $this->render('index', ['matchesArr' => $matches]);
        }
        return $this->redirect('/');
    }

    public function actionSettings()
    {
        if (\Yii::$app->user->can('sAdminMenu')) {
            $selects = Select::findAll(['parent_id' => null]);
            return $this->render('settings', ['selects' => $selects]);
        }
    }

    public function actionCheckSelect()
    {
        if (\Yii::$app->user->can('sAdminMenu')) {
            $id = \Yii::$app->request->get('id');
            $state = \Yii::$app->request->get('state');

            $select = Select::findOne($id);
            $select->lineups_parse = $state;
            $select->save();
        }
    }

    public function actionMatchSubscribe()
    {
        if (\Yii::$app->user->can('lineupsMatches')) {
            $id = \Yii::$app->request->get('id');
            $state = \Yii::$app->request->get('state');

            if ($state == 1) {
                \Yii::$app->db->createCommand()->insert('user2matches_lineups', [
                    'match_id' => $id,
                    'user_id' => \Yii::$app->user->id,
                ])->execute();
            } else {
                \Yii::$app->db->createCommand()->delete('user2matches_lineups', [
                    'match_id' => $id,
                    'user_id' => \Yii::$app->user->id,
                ])->execute();
            }
        }
    }

    public function actionMatchSubscribeAll()
    {
        if (\Yii::$app->user->can('lineupsMatches')) {
            $state = \Yii::$app->request->get('state');

            $matches = MatchesLineups::find()
                ->select('id')
                ->where(['source' => null])
                ->all();
            $matchesArr = [];
            $matchesIds = [];
            if ($state == 1) {
                foreach ($matches as $match) {
                    if ($match->status === false) {
                        $matchesArr[] = [\Yii::$app->user->id, $match->id, 0];
                        $matchesIds[] = $match->id;
                    }
                }
                \Yii::$app->db->createCommand()->batchInsert('user2matches_lineups', ['user_id', 'match_id', 'status'], $matchesArr)
                    ->execute();
                $user = User::findOne(\Yii::$app->user->id);
                $user->lineups_subscribe = 1;
                $user->save();
            } else {
                foreach ($matches as $match) {
                    $matchesArr[] = [\Yii::$app->user->id, $match->id, 0];
                    $matchesIds[] = $match->id;
                }

                \Yii::$app->db->createCommand()->delete('user2matches_lineups', [
                    'user_id' => \Yii::$app->user->id,
                ])->execute();

                $user = User::findOne(\Yii::$app->user->id);
                $user->lineups_subscribe = 0;
                $user->save();
            }
            return json_encode($matchesIds);
        }
    }

    public function actionTest()
    {
        $matches = MatchesLineups::find()->where([
            'and', ['source' => null], ['and', ['>', 'date', time()], ['<', 'date', time() + 5400]]
        ])->all();

        foreach ($matches as $match) {
            $lineupsMatchParser = new LineupsMatchParser($match);
            $lineupsMatchParser->check();
        }
    }
}

views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

?>
<div class="content-wrapper">
    <section class="content-header">
        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
                    echo \yii\helpers\Html::encode($this->title);
                } else {
                    echo \yii\helpers\Inflector::camel2words(
                        \yii\helpers\Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                } ?>
            </h1>
        <?php } ?>

        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>

<footer class="main-footer">

</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark" id="saved-matches-sidebar">
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane active" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Сохраненные матчи</h3>
            <ul class='control-sidebar-menu' id="saved-matches-container" style="margin: 0 0 0 0;">
                <?php if (isset($this->params['savedMatches']) && $this->params['savedMatches']): ?>
                    <?php foreach ($this->params['savedMatches'] as $cup => $matches): ?>
                    <span class="control-sidebar-subheading"><?= $cup ?></span>
                        <?php foreach ($matches as $match): ?>
                            <li>
                                <a style="color: white; float: left" data-url="<?= $match['url'] ?>" href="/?matchUrl=<?= $match['url'] ?>"><?= $match['name'] ?></a>
                                <span class="text-red del-saved-match" data-id="<?= $match['id'] ?>" style="z-index: 11111111; display: inline-block; cursor: pointer;">
                                    <i class="fa fa-trash-o"></i>
                                </span>
                            </li>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </ul>
            <!-- /.control-sidebar-menu -->
            <!-- /.control-sidebar-menu -->

        </div>
    </div>
</aside><!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class='control-sidebar-bg' id="saved-matches-sidebar"></div>

views/layouts/header.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */
?>

<header class="main-header">

    <?= Html::a('<span class="logo-mini">MTP</span><span class="logo-lg">' . Yii::$app->name . '</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">

        <?php if(Yii::$app->user->can('sAdminMenu')): ?>
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
        <?php endif; ?>
        <div class="col-md-5">
        <?php
        if (Yii::$app->controller->id == 'site' and Yii::$app->controller->action->id = 'index') {
            echo \kartik\nav\NavX::widget([
                'options' => ['class' => 'nav nav-pills', 'id' => 'match-select'],
                'items' => ['label' => '<input id="match-count" class="form-control nav-match-count-input" type="number" min="0" max="5" value="' . $this->params['matchCount'] . '">'] + $this->params['selectArr'],
            ]);
        }
        ?>
        </div>
        <div class="navbar-custom-menu">

            <ul class="nav navbar-nav">
                <?php if (Yii::$app->controller->id == 'site' and Yii::$app->controller->action->id = 'index'): ?>
                    <li>
                        <a href="#" target="_blank" id="soccerwy-link" ><i class="fa fa-refresh fa-spin hidden"></i>Soccerway</a>
                    </li>
                    <li class="disabled">
                        <a href="#" target="_blank" id="betexplorer-link" ><i class="fa fa-refresh fa-spin hidden"></i>Betexplorer</a>
                    </li>
                    <li class="disabled">
                        <a href="#" target="_blank" id="oddsportal-link"><i class="fa fa-refresh fa-spin hidden"></i>Oddsportal</a>
                    </li>
                    <li>
                        <a href="#" id="get-transfermarkt"><i class="fa fa-refresh fa-spin hidden"></i>Transfermarkt</a>
                    </li>
                    <li>
                        <a href="#" id="save">Сохранить</a>
                    </li>
                <?php endif; ?>
                <?php if (\Yii::$app->user->can('incidentsMatches')): ?>
                    <li class="dropdown notifications-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            <i class="fa fa-flag-o"></i>
                            <span class="label label-warning" id="replacements-count">0</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">Последние события</li>
                            <li id="replacements">

                            </li>
                            <li class="footer"><a href="/replacements">View all</a></li>
                        </ul>
                    </li>
                <?php endif; ?>
                <?php if (\Yii::$app->user->can('lineupsMatches')): ?>
                    <li class="dropdown notifications-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            <i class="fa fa-bell-o"></i>
                            <span class="label label-warning" id="notifications-count">0</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">Непросмотренные матчи</li>
                            <li id="notifications">

                            </li>
                            <li class="footer"><a href="/lineups">View all</a></li>
                        </ul>
                    </li>
                <?php endif; ?>
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="/img/user.png" class="user-image" alt="User Image"/>
                        <span class="hidden-xs"><?= Yii::$app->user->identity->username ?></span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="/img/user.png" class="img-circle"
                                 alt="User Image"/>
                            <p>
                                <?= Yii::$app->user->identity->username ?>
                                <small><?= Yii::$app->user->identity->email ?></small>
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">

                            <div class="pull-right">
                                <?= Html::a(
                                    'Sign out',
                                    ['/site/logout'],
                                    ['data-method' => 'post', 'class' => 'btn btn-default btn-flat']
                                ) ?>
                            </div>
                        </li>
                    </ul>
                </li>

                <!-- User Account: style can be found in dropdown.less -->
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-save"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

views/layouts/left.php
<aside class="main-sidebar">

    <section class="sidebar">

        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="/img/user.png" class="img-circle" alt="User Image"/>
            </div>
            <div class="pull-left info">
                <p><?= Yii::$app->user->identity->username ?></p>
            </div>
        </div>

        <?= dmstr\widgets\Menu::widget(
            [
                'options' => ['class' => 'sidebar-menu tree', 'data-widget'=> 'tree'],
                'items' => [
                    ['label' => 'Menu', 'options' => ['class' => 'header']],
                    ['label' => 'Users', 'icon' => 'fa fa-user', 'url' => ['/user']],
                    ['label' => 'RBAC',
                        'items' => [
                            ['label' => 'Rule', 'url' => ['/rbac/rule']],
                            ['label' => 'Permission', 'url' => ['/rbac/permission']],
                            ['label' => 'Role', 'url' => ['/rbac/role']],
                            ['label' => 'Assigment', 'url' => ['/rbac/assignment']],
                        ]
                    ],
                    ['label' => 'LineupsSettings', 'icon' => 'fa fa-gear', 'url' => ['/lineups/settings']],
                    ['label' => 'IncidentsSettings', 'icon' => 'fa fa-gear', 'url' => ['/replacements/settings']],
                ],
            ]
        ) ?>

    </section>

</aside>

views/layouts/main-login.php
<?php
use app\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */


if (Yii::$app->controller->action->id === 'login') { 
/**
 * Do not use this code in your template. Remove it. 
 * Instead, use the code  $this->layout = '//main-login'; in your controller.
 */
    echo $this->render(
        'main-login',
        ['content' => $content]
    );
} else {

    if (class_exists('backend\assets\AppAsset')) {
        backend\assets\AppAsset::register($this);
    } else {
        app\assets\AppAsset::register($this);
    }

    dmstr\web\AdminLteAsset::register($this);

    $directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body class="hold-transition skin-blue <?php if(Yii::$app->user->can('sAdminMenu')): ?>sidebar-mini<?php endif;?> sidebar-collapse">
    <?php $this->beginBody() ?>
    <div class="wrapper">

        <?= $this->render(
            'header.php',
            ['directoryAsset' => $directoryAsset]
        ) ?>

        <?php if(Yii::$app->user->can('sAdminMenu')): ?>
            <?= $this->render(
                'left.php',
                ['directoryAsset' => $directoryAsset]
            )
            ?>
        <?php endif; ?>

        <?= $this->render(
            'content.php',
            ['content' => $content, 'directoryAsset' => $directoryAsset]
        ) ?>

    </div>
    <audio id="notification-audio" src="/notification.mp3"></audio>
    <div class="modal fade" id="modal-notification" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Уведомления.</h4>
                </div>
                <div class="modal-body">
                    <h4 class="modal-title">Новые стартовые составы</h4>
                    <div id="lineups-container"></div>
                    <br>
                    <h4 class="modal-title">Новые события</h4>
                    <div id="replacements-container"></div>
                    <?php if (Yii::$app->user->can('sAdminMenu')): ?>
                        <br>
                        <h4 class="modal-title">Оповещения</h4>
                        <div id="admin-notification-container"></div>
                    <?php endif; ?>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal-yellow-cards" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

    </div>
    <?php $this->endBody() ?>
    </body>
    </html>
    <?php $this->endPage() ?>
<?php } ?>