models/MatchesLineups.php
<?php

namespace app\models;

use Yii;
use yii\db\Query;

/**
 * This is the model class for table "matches_lineups".
 *
 * @property int $id
 * @property string $team_1
 * @property int $team_1_id
 * @property string $team_2
 * @property int $team_2_id
 * @property string $url
 * @property int $soccerway_id
 * @property int $team_1_changes
 * @property int $team_2_changes
 * @property string $source
 * @property string $players_json
 * @property int $select_id
 * @property int $date
 * @property int $besoccer_name_mark_team_1
 * @property int $besoccer_name_mark_team_2
 * @property int $sofascore_name_mark_team_1
 * @property int $sofascore_name_mark_team_2
 *
 * @property Select $select
 */
class MatchesLineups extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'matches_lineups';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['team_1', 'team_2', 'url', 'soccerway_id', 'date'], 'required'],
            [['soccerway_id', 'team_1_id', 'team_2_id', 'team_1_changes', 'team_2_changes', 'select_id', 'date', 'sofascore_name_mark_team_1', 'sofascore_name_mark_team_2', 'besoccer_name_mark_team_1', 'besoccer_name_mark_team_2'], 'integer'],
            [['players_json'], 'string'],
            [['team_1', 'team_2', 'url', 'source'], 'string', 'max' => 255],
            [['soccerway_id'], 'unique'],
            [['select_id'], 'exist', 'skipOnError' => true, 'targetClass' => Select::className(), 'targetAttribute' => ['select_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'team_1' => 'Team 1',
            'team_1_id' => 'Team 1 Id',
            'team_2' => 'Team 2',
            'team_2_id' => 'Team 2 Id',
            'url' => 'Url',
            'soccerway_id' => 'Soccerway ID',
            'team_1_changes' => 'Team 1 Changes',
            'team_2_changes' => 'Team 2 Changes',
            'source' => 'Source',
            'players_json' => 'Players Json',
            'select_id' => 'Select ID',
            'date' => 'Date',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSelect()
    {
        return $this->hasOne(Select::className(), ['id' => 'select_id']);
    }

    public function getSubscribeUsers()
    {
        return $this->hasMany(User::className(), ['id' => 'user_id'])
            ->viaTable('user2matches_lineups', ['match_id' => 'id']);
    }

    public function getUserSubscribe()
    {
        if ((new \yii\db\Query())
            ->from('user2matches_lineups')
            ->where(['match_id' => $this->id, 'user_id' => Yii::$app->user->id])
            ->one()){
            return true;
        }
        return false;
    }

    public function getStatus()
    {
        $query = (new Query())
            ->select('status')
            ->from('user2matches_lineups')
            ->where(['match_id' => $this->id, 'user_id' => \Yii::$app->user->id])
            ->column();
        return (!empty($query)) ? $query[0] : false;
    }

    public function getTeam1Name()
    {
        return $this->hasOne(Team::className(), ['team_1_id' => 'id']);
    }

    public function getTeam2Name()
    {
        return $this->hasOne(Team::className(), ['team_2_id' => 'id']);
    }
}

controllers/LineupsController.php
<?php
/**
 * Created by PhpStorm.
 * User: Ivan
 * Date: 15.06.2018
 * Time: 7:44
 */

namespace app\controllers;

use app\components\LineupsParser;
use app\models\MatchesLineups;
use app\models\Select;
use app\models\User;
use yii\db\Query;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

class LineupsController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => [
                            'index',
                            'settings',
                            'check-select',
                            'match-subscribe',
                            'match-subscribe-all',
                            'match-subscribe-all',
                            'test'
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        if (\Yii::$app->user->can('lineupsMatches')) {
            $matches = MatchesLineups::find()->where(['and', ['>', 'date', time() - 7200], ['<', 'date', time() + 14400]])->orderBy('date')->all();

            return $this->render('index', ['matchesArr' => $matches]);
        }
        return $this->redirect('/');
    }

    public function actionSettings()
    {
        if (\Yii::$app->user->can('sAdminMenu')) {
            $selects = Select::findAll(['parent_id' => null]);
            return $this->render('settings', ['selects' => $selects]);
        }
    }

    public function actionCheckSelect()
    {
        if (\Yii::$app->user->can('sAdminMenu')) {
            $id = \Yii::$app->request->get('id');
            $state = \Yii::$app->request->get('state');

            $select = Select::findOne($id);
            $select->lineups_parse = $state;
            $select->save();
        }
    }

    public function actionMatchSubscribe()
    {
        if (\Yii::$app->user->can('lineupsMatches')) {
            $id = \Yii::$app->request->get('id');
            $state = \Yii::$app->request->get('state');

            if ($state == 1) {
                \Yii::$app->db->createCommand()->insert('user2matches_lineups', [
                    'match_id' => $id,
                    'user_id' => \Yii::$app->user->id,
                ])->execute();
            } else {
                \Yii::$app->db->createCommand()->delete('user2matches_lineups', [
                    'match_id' => $id,
                    'user_id' => \Yii::$app->user->id,
                ])->execute();
            }
        }
    }

    public function actionMatchSubscribeAll()
    {
        if (\Yii::$app->user->can('lineupsMatches')) {
            $state = \Yii::$app->request->get('state');

            $matches = MatchesLineups::find()
                ->select('id')
                ->where(['source' => null])
                ->all();
            $matchesArr = [];
            $matchesIds = [];
            if ($state == 1) {
                foreach ($matches as $match) {
                    if ($match->status === false) {
                        $matchesArr[] = [\Yii::$app->user->id, $match->id, 0];
                        $matchesIds[] = $match->id;
                    }
                }
                \Yii::$app->db->createCommand()->batchInsert('user2matches_lineups', ['user_id', 'match_id', 'status'], $matchesArr)
                    ->execute();
                $user = User::findOne(\Yii::$app->user->id);
                $user->lineups_subscribe = 1;
                $user->save();
            } else {
                foreach ($matches as $match) {
                    $matchesArr[] = [\Yii::$app->user->id, $match->id, 0];
                    $matchesIds[] = $match->id;
                }

                \Yii::$app->db->createCommand()->delete('user2matches_lineups', [
                    'user_id' => \Yii::$app->user->id,
                ])->execute();

                $user = User::findOne(\Yii::$app->user->id);
                $user->lineups_subscribe = 0;
                $user->save();
            }
            return json_encode($matchesIds);
        }
    }

    public function actionTest()
    {
        $matches = MatchesLineups::find()->where([
            'and', ['source' => null], ['and', ['>', 'date', time()], ['<', 'date', time() + 5400]]
        ])->all();

        foreach ($matches as $match) {
            $lineupsMatchParser = new LineupsMatchParser($match);
            $lineupsMatchParser->check();
        }
    }
}

views/lineups/_lineups_matches.php
<?php foreach ($matchesArr as $match): ?>
    <tr data-id="<?= $match->id ?>" class="<?php if($match->status == 1 || $match->status == 2) {echo 'has-lineups ';}?>" data-time="<?= $match->date ?>000">
        <td style="width: 20%;">
            <div class="text-center">
                <?= $match->select->parent->name ?> - <?= $match->select->name ?>
            </div>
        </td>
        <td style="width: 30%;">
            <div class="text-right">
                <?php if ($match->besoccer_name_mark_team_1): ?><img src="/img/besoccer.ico" style="height: 20px"><?php endif; ?>
                <?php if ($match->sofascore_name_mark_team_1): ?><img src="/img/sofascore.ico" style="height: 20px"><?php endif; ?>
                <a href="/?matchUrl=<?= $match->url ?><?php if(!is_null($match->players_json)) {echo '&lineups='.$match->id;} ?>" target="_blank">
                    <span class="text-red"><?= $match->team_1_changes ?? ''?></span> <?= $match->team_1 ?>
                </a>
            </div>
        </td>
        <td style="width: 5%;">
            <div class="text-center">
                <?php if($match) ?>
                <a href="/?matchUrl=<?= $match->url ?><?php if(!is_null($match->players_json)) {echo '&lineups='.$match->id;} ?>" target="_blank">
                    <?= (new DateTime('@'.$match['date']))->setTimezone((new \DateTimeZone(Yii::$app->user->identity->timezone)))->format('H:i'); ?>
                </a>
            </div>
        </td>
        <td style="width: 30%;">
            <div class="text-left">
                <a href="/?matchUrl=<?= $match->url ?><?php if(!is_null($match->players_json)) {echo '&lineups='.$match->id;} ?>" target="_blank">
                    <?= $match->team_2 ?> <span class="text-red"><?= $match->team_2_changes ?? '' ?></span>
                </a>
                <?php if ($match->besoccer_name_mark_team_2): ?><img src="/img/besoccer.ico" style="height: 20px"><?php endif; ?>
                <?php if ($match->sofascore_name_mark_team_2): ?><img src="/img/sofascore.ico" style="height: 20px"><?php endif; ?>
            </div>
        </td>
        <td style="width: 15%;">
            <div class="checkbox no-margin">
                <label>
                    <input id="subscribe-checkbox" class="<?php if($match->source){echo 'has-changes';} ?>" data-id="<?= $match->id ?>" type="checkbox" <?php if($match->userSubscribe):?> checked <?php endif; ?>>
                </label>
            </div>
        </td>
    </tr>

<?php endforeach; ?>

views/lineups/index.php
<?php
/**
 * Created by PhpStorm.
 * User: Ivan
 * Date: 21.06.2018
 * Time: 8:05
 */

/**@var $match \app\models\MatchesLineups**/
$this->title = 'Lineups - '.Yii::$app->name;
$this->blocks['content-header'] = '';
?>
<div class="row">
    <div class="box">
        <div class="box-body no-padding">
        <table class="table" id="lineups-table">
            <thead>
                <tr>
                    <td style="width: 20%"></td>
                    <td style="width: 30%"></td>
                    <td style="width: 5%"></td>
                    <td style="width: 30%"></td>
                    <td style="width: 15%">
                        <div class="checkbox no-margin">
                            <label><input id="subscribe-checkbox-all" <?php if(\Yii::$app->user->identity->lineups_subscribe): ?>checked<?php endif; ?> type="checkbox">Подписаться на все</label>
                        </div>
                    </td>
                </tr>
            </thead>
            <tbody>
            <?php include '_lineups_matches.php' ?>
            </tbody>
        </table>
        </div>
    </div>
</div>

views/lineups/settings.php
<?php
/**
 * Created by PhpStorm.
 * User: Ivan
 * Date: 21.06.2018
 * Time: 6:47
 */
/**@var $select \app\models\Select**/
?>

<div class="row">
    <?php foreach ($selects as $select): ?>
    <div class="col-md-4">
        <div class="box box-primary collapsed-box">
            <div class="box-header with-border">
                <h3 class="box-title"><?= $select->name ?></h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i>
                    </button>
                </div>
            </div>
            <div class="box-body" style="display: none;">
                <?php foreach ($select->selects as $secondSelect): ?>
                <div class="box box-success collapsed-box">
                    <div class="box-header with-border">
                        <h3 class="box-title"><?= $secondSelect->name ?></h3>

                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="box-body" style="display: none;">
                        <?php foreach ($secondSelect->selects as $thirdSelect): ?>
                        <div class="box box-default collapsed-box">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= $thirdSelect->name ?></h3>
                                <div class="box-tools pull-right">
                                    <div class="checkbox">
                                        <label>
                                            <input id="select-checkbox" data-id="<?= $thirdSelect->id ?>" type="checkbox" <?php if($thirdSelect->lineups_parse):?> checked <?php endif;?>>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php endforeach; ?>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <?php endforeach; ?>
</div>